version: 2
jobs:
 build:
   docker:
     # using custom image, see .circleci/images/primary/Dockerfile
     - image: docker/compose:1.16.1
   working_directory: /app

   steps:
     - checkout

     - setup_remote_docker

     - run:
         name: Build docker-compose containers
         command: |
           docker-compose build

     - run:
         name: Start containers
         command: |
           docker-compose up -d

     - run:
          name: Install awscli
          command: sudo pip install awscli