version: 2
jobs:
 build:
   docker:
     - image: python:3.7
   working_directory: /app

   steps:
     - checkout

     - setup_remote_docker

     - run: 
        name: Pull project
        command: ssh -o "StrictHostKeyChecking no" ec2-user@ec2-35-158-219-60.eu-central-1.compute.amazonaws.com "cd WeLeave && git status"
