uber_app_id:  ""
number_of_iteration: 15
delta_between_requests: 120
mongodb_host: "mongodb"
mongodb_port: 27017
apps:
- uber
- marcel
- snapcar
- allocab
- g7
- drive
- citybird
- felix
- lecab
- taxify
- talixo
- backlane
api_hostname: "http://0.0.0.0:5000"
log_in_file: False